# Generated by Django 3.2 on 2021-10-23 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('nickname', models.CharField(default='', max_length=32)),
                ('super_admin', models.BooleanField(default=False)),
                ('admin_type', models.CharField(default='', max_length=32)),
                ('mobile', models.TextField(null=True)),
                ('token', models.TextField(null=True)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
