# Generated by Django 3.2 on 2022-01-03 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=32)),
                ('success_num', models.IntegerField(default=0)),
                ('error_num', models.IntegerField(default=0)),
                ('sum_num', models.IntegerField(default=0)),
                ('status', models.TextField(default='offline')),
                ('timer_type', models.TextField(null=True)),
                ('timer_value', models.TextField(null=True)),
                ('timer_switch', models.TextField(default='', null=True)),
                ('ding_token', models.TextField(default='', null=True)),
                ('ding_switch', models.TextField(default='', null=True)),
                ('owner', models.TextField(null=True)),
                ('task_user', models.TextField(default='')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTaskCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=32)),
                ('apiname', models.CharField(max_length=32)),
                ('casename', models.TextField(default='用例1')),
                ('status', models.TextField(default='待执行')),
                ('case_type', models.TextField(default='Get')),
                ('request_content', models.TextField(null=True)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTaskCaseAssert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=32)),
                ('apiname', models.CharField(max_length=32)),
                ('casename', models.TextField(default='用例1')),
                ('parameter', models.TextField(default='code')),
                ('value', models.TextField(default='200')),
                ('assert_type', models.TextField(default='==')),
                ('assert_type_id', models.TextField(default='')),
                ('assert_id', models.TextField(default='')),
                ('parameter_id', models.TextField(default='')),
                ('value_id', models.TextField(default='')),
                ('debug_id', models.TextField(default='')),
                ('del_id', models.TextField(default='')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTaskContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_id', models.TextField(default='NA')),
                ('taskname', models.CharField(max_length=32)),
                ('apiname', models.CharField(max_length=32)),
                ('url', models.TextField(default='')),
                ('status', models.TextField(default='待执行')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTaskResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_id', models.TextField(default='')),
                ('taskname', models.TextField()),
                ('apiname', models.TextField()),
                ('casename', models.TextField()),
                ('status', models.TextField()),
                ('parameter', models.TextField()),
                ('assert_type', models.TextField()),
                ('pre_value', models.TextField()),
                ('final_value', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
                ('runner', models.TextField(default='自动化')),
                ('error', models.TextField(default='')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTaskUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('avatar', models.TextField(null=True)),
                ('role', models.CharField(max_length=64)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.TextField(null=True)),
                ('username', models.CharField(max_length=32)),
                ('page', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=32)),
                ('content', models.TextField(null=True)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('nickname', models.CharField(default='', max_length=32)),
                ('avatar', models.TextField(null=True)),
                ('super_admin', models.BooleanField(default=False)),
                ('admin_type', models.CharField(default='', max_length=32)),
                ('mobile', models.TextField(null=True)),
                ('token', models.TextField(null=True)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
