# Generated by Django 3.2 on 2022-01-06 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('directory_name', models.CharField(max_length=64)),
                ('file_num', models.IntegerField(default=0)),
                ('file_size', models.TextField(null=True)),
                ('creater', models.CharField(max_length=64)),
                ('member', models.TextField(null=True)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
