# Generated by Django 3.2 on 2021-11-29 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=32)),
                ('success_num', models.IntegerField(default=0)),
                ('error_num', models.IntegerField(default=0)),
                ('sum_num', models.IntegerField(default=0)),
                ('status', models.TextField(default='offline')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.TextField(null=True)),
                ('username', models.CharField(max_length=32)),
                ('page', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=32)),
                ('content', models.TextField(null=True)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(null=True),
        ),
    ]
