# Generated by Django 3.2 on 2022-01-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0002_directoryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryinfo',
            name='member1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='directoryinfo',
            name='member2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='directoryinfo',
            name='member3',
            field=models.TextField(default=''),
        ),
    ]
