# Generated by Django 3.2 on 2021-11-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0002_auto_20211129_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='timer_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='timer_value',
            field=models.TextField(null=True),
        ),
    ]
