# Generated by Django 3.2 on 2021-12-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0003_auto_20211130_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='owner',
            field=models.TextField(null=True),
        ),
    ]
