# Generated by Django 3.2 on 2022-01-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0003_auto_20220106_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryinfo',
            name='file_size',
            field=models.TextField(default=''),
        ),
    ]
