# Generated by Django 3.2 on 2022-01-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0004_alter_directoryinfo_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryinfo',
            name='file_size',
            field=models.TextField(default='0'),
        ),
    ]
