# Generated by Django 3.2 on 2022-01-06 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0005_alter_directoryinfo_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('directory_name', models.CharField(max_length=64)),
                ('file_name', models.CharField(max_length=64)),
                ('file_type', models.CharField(max_length=64)),
                ('file_size', models.CharField(max_length=64)),
                ('file_link', models.TextField(null=True)),
                ('creater', models.CharField(max_length=64)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
