# Generated by Django 3.2 on 2021-12-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0006_automationtaskcase_automationtaskcaseassert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtaskcaseassert',
            name='assert_type',
            field=models.TextField(default='=='),
        ),
        migrations.AlterField(
            model_name='automationtaskcaseassert',
            name='parameter',
            field=models.TextField(default='code'),
        ),
        migrations.AlterField(
            model_name='automationtaskcaseassert',
            name='value',
            field=models.TextField(default='200'),
        ),
    ]
