# Generated by Django 3.2 on 2021-12-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0007_auto_20211205_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutomationTaskCaseAssert',
        ),
        migrations.AddField(
            model_name='automationtaskcase',
            name='assert_type',
            field=models.TextField(default='=='),
        ),
        migrations.AddField(
            model_name='automationtaskcase',
            name='parameter',
            field=models.TextField(default='code'),
        ),
        migrations.AddField(
            model_name='automationtaskcase',
            name='value',
            field=models.TextField(default='200'),
        ),
    ]
