# Generated by Django 3.2 on 2022-01-09 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='APK',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apkname', models.CharField(max_length=64)),
                ('project', models.CharField(max_length=64)),
                ('env', models.CharField(max_length=64)),
                ('platform', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('size', models.TextField(null=True)),
                ('apklink', models.CharField(max_length=64)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
