# Generated by Django 3.2 on 2021-12-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0009_auto_20211205_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtaskcaseassert',
            name='casename',
            field=models.TextField(null=True),
        ),
    ]
