# Generated by Django 3.2 on 2022-01-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0009_apk'),
    ]

    operations = [
        migrations.AddField(
            model_name='apk',
            name='remark',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='apk',
            name='status',
            field=models.TextField(default='下线'),
        ),
    ]
