# Generated by Django 3.2 on 2021-12-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0010_automationtaskcaseassert_casename'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtaskcase',
            name='casename',
            field=models.TextField(null=True),
        ),
    ]
