# Generated by Django 3.2 on 2022-01-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0010_auto_20220109_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apk',
            name='status',
            field=models.TextField(default='未上线'),
        ),
    ]
