# Generated by Django 3.2 on 2021-12-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0011_automationtaskcase_casename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtaskcase',
            name='casename',
            field=models.TextField(default='用例1'),
        ),
        migrations.AlterField(
            model_name='automationtaskcaseassert',
            name='casename',
            field=models.TextField(default='用例1'),
        ),
    ]
