# Generated by Django 3.2 on 2022-01-19 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0011_alter_apk_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressTestTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=64)),
                ('creater', models.CharField(max_length=64)),
                ('report_num', models.IntegerField(default=0)),
                ('status', models.TextField(default='待执行')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('utime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
