# Generated by Django 3.2 on 2022-01-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0012_stresstesttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='stresstesttask',
            name='machine',
            field=models.TextField(default='未分配'),
        ),
    ]
