# Generated by Django 3.2 on 2021-12-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0012_auto_20211212_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationtaskcase',
            name='casenum',
        ),
        migrations.RemoveField(
            model_name='automationtaskcaseassert',
            name='casenum',
        ),
    ]
