# Generated by Django 3.2 on 2022-01-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0013_stresstesttask_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='stresstesttask',
            name='api_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stresstesttask',
            name='model',
            field=models.TextField(default='未指定'),
        ),
    ]
