# Generated by Django 3.2 on 2021-12-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0013_auto_20211212_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationtaskcase',
            name='url',
        ),
    ]
