# Generated by Django 3.2 on 2021-12-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0014_remove_automationtaskcase_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtaskreport',
            name='report_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='automationtaskreport',
            name='sum_num',
            field=models.IntegerField(default=0),
        ),
    ]
