# Generated by Django 3.2 on 2022-01-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0014_auto_20220120_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='stresstesttask',
            name='tech',
            field=models.TextField(default='Jmeter'),
        ),
    ]
