# Generated by Django 3.2 on 2021-12-12 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0015_auto_20211212_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTaskResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=32)),
                ('apiname', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=32)),
                ('report_id', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('runner', models.TextField(default='自动化')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='AutomationTaskReport',
        ),
    ]
