# Generated by Django 3.2 on 2021-12-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0016_auto_20211212_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtaskcaseassert',
            name='assert_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='automationtaskcaseassert',
            name='debug_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='automationtaskcaseassert',
            name='del_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='automationtaskcaseassert',
            name='parameter_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='automationtaskcaseassert',
            name='value_id',
            field=models.TextField(default=''),
        ),
    ]
