# Generated by Django 3.2 on 2021-12-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0017_auto_20211213_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtaskcaseassert',
            name='assert_type_id',
            field=models.TextField(default=''),
        ),
    ]
