# Generated by Django 3.2 on 2021-12-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0019_alter_automationtaskcontent_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutomationTaskResult',
        ),
    ]
