# Generated by Django 3.2 on 2021-12-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0023_auto_20211225_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtaskcontent',
            name='run_id',
            field=models.TextField(default='NA'),
        ),
    ]
