# Generated by Django 3.2 on 2021-12-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0024_alter_automationtaskcontent_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtaskresult',
            name='error',
            field=models.TextField(default=''),
        ),
    ]
