# Generated by Django 2.2.6 on 2019-11-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('build_num', models.TextField()),
                ('package_name', models.TextField()),
                ('apk_name', models.CharField(max_length=255, unique=True)),
                ('version', models.TextField()),
                ('version_code', models.TextField()),
                ('size', models.TextField()),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_name', models.TextField()),
                ('dex', models.TextField()),
                ('so', models.TextField()),
                ('png', models.TextField()),
                ('xml', models.TextField()),
                ('arsc', models.TextField()),
                ('jar', models.TextField()),
                ('SF', models.TextField()),
                ('MF', models.TextField()),
                ('kotlin_metadata', models.TextField()),
                ('jpg', models.TextField()),
                ('gz', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
                ('super_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
