# Generated by Django 2.2.6 on 2020-01-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_sample_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.TextField()),
                ('country', models.TextField()),
                ('ip', models.TextField()),
                ('gaid', models.TextField()),
                ('ad_size', models.TextField()),
                ('title', models.TextField()),
                ('desc_str', models.TextField()),
                ('image_url', models.TextField()),
                ('click_url', models.TextField()),
                ('request_time', models.DateTimeField()),
                ('dt', models.DateField()),
                ('is_html', models.TextField()),
                ('html_str', models.TextField()),
                ('dsp_or_ssp', models.TextField()),
                ('creative_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ad_sample_stat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt', models.DateField()),
                ('source_name', models.TextField()),
                ('loc', models.TextField()),
                ('req', models.IntegerField()),
                ('suc', models.IntegerField()),
                ('fail', models.IntegerField()),
            ],
        ),
    ]
