# Generated by Django 2.2 on 2020-03-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0002_ad_sample_info_ad_sample_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartUpTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pkgname', models.TextField()),
                ('apkname', models.TextField()),
                ('version', models.TextField()),
                ('firsttime', models.TextField()),
                ('secondtime', models.TextField()),
                ('ctime', models.DateTimeField()),
            ],
        ),
    ]
