# Generated by Django 2.2.3 on 2020-03-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0003_startuptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pkgname', models.TextField()),
                ('apkname', models.TextField()),
                ('version', models.TextField()),
                ('logname', models.TextField()),
                ('ctime', models.DateTimeField()),
            ],
        ),
    ]
