# Generated by Django 2.2.3 on 2020-03-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0004_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startuptime',
            name='firsttime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='startuptime',
            name='secondtime',
            field=models.IntegerField(),
        ),
    ]
