# Generated by Django 2.2.3 on 2020-03-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0005_auto_20200312_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pkgname', models.TextField()),
                ('version', models.TextField()),
                ('logname', models.TextField()),
                ('remark', models.TextField()),
                ('ctime', models.DateTimeField()),
            ],
        ),
    ]
