# Generated by Django 2.2.3 on 2020-03-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0006_applog'),
    ]

    operations = [
        migrations.CreateModel(
            name='APImoitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('api', models.TextField()),
                ('errortimes', models.TextField()),
                ('errortype', models.TextField()),
                ('ctime', models.DateTimeField()),
            ],
        ),
    ]
