# Generated by Django 2.2.3 on 2020-03-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0007_apimoitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimoitor',
            name='errortimes',
            field=models.IntegerField(),
        ),
    ]
