# Generated by Django 2.2.3 on 2020-03-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0008_auto_20200314_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimoitor',
            name='datetime',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='performance',
            name='remark',
            field=models.TextField(default=''),
        ),
    ]
