# Generated by Django 2.2.6 on 2020-03-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0009_auto_20200317_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=32),
        ),
    ]
