# Generated by Django 2.2.3 on 2020-03-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0011_auto_20200327_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='applog',
            name='did',
            field=models.TextField(default=''),
        ),
    ]
