# Generated by Django 2.2.3 on 2020-04-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0012_applog_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='gif',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='size',
            name='kotlin_builtins',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='size',
            name='kotlin_module',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='size',
            name='mp4',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='size',
            name='properties',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='size',
            name='webp',
            field=models.TextField(default='0'),
        ),
    ]
