# Generated by Django 2.2.3 on 2020-04-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0013_auto_20200402_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIcase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('env', models.TextField()),
                ('api', models.IntegerField()),
                ('taskname', models.TextField()),
                ('creater', models.TextField()),
                ('check_data', models.TextField()),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='APIinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('env', models.TextField()),
                ('api', models.IntegerField()),
                ('request_name', models.TextField()),
                ('response_name', models.TextField()),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='APItask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('env', models.TextField()),
                ('taskname', models.IntegerField()),
                ('creater', models.TextField()),
                ('ctime', models.DateTimeField()),
            ],
        ),
    ]
