# Generated by Django 2.2.3 on 2020-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0014_apicase_apiinfo_apitask'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitask',
            name='timercheck',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='apitask',
            name='timetype',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='apitask',
            name='timevalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='api',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='api',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apitask',
            name='taskname',
            field=models.TextField(),
        ),
    ]
