# Generated by Django 2.2.3 on 2020-04-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0015_auto_20200406_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_applog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('logcontent', models.TextField()),
                ('logtime', models.DateTimeField()),
            ],
        ),
    ]
