# Generated by Django 2.2.3 on 2020-04-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0016_server_applog'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_applog',
            name='anm',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='server_applog',
            name='type',
            field=models.TextField(default=''),
        ),
    ]
