# Generated by Django 2.2.3 on 2020-04-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0017_auto_20200414_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_applog',
            name='did',
            field=models.TextField(default=''),
        ),
    ]
