# Generated by Django 2.2.3 on 2020-04-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0018_server_applog_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_applog',
            name='brd',
            field=models.TextField(default=''),
        ),
    ]
