# Generated by Django 2.2.3 on 2020-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0019_server_applog_brd'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_applog',
            name='action',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='server_applog',
            name='cha',
            field=models.TextField(default=''),
        ),
    ]
