# Generated by Django 2.2.3 on 2020-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0020_auto_20200416_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_applog',
            name='ver',
            field=models.TextField(default=''),
        ),
    ]
