# Generated by Django 2.2.3 on 2020-04-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0021_server_applog_ver'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitask',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
