# Generated by Django 2.2.3 on 2020-04-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0022_apitask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitask',
            name='status',
            field=models.TextField(default='None'),
        ),
    ]
