# Generated by Django 2.2.3 on 2020-05-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0023_auto_20200427_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
