# Generated by Django 2.2.3 on 2020-05-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0024_apiinfo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskresult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('env', models.TextField()),
                ('taskname', models.TextField()),
                ('status', models.TextField()),
                ('result', models.TextField()),
                ('ctime', models.DateTimeField()),
            ],
        ),
    ]
