# Generated by Django 2.2.6 on 2020-06-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0026_apitask_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='status',
            field=models.TextField(default='Online'),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='errorcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='passcount',
            field=models.IntegerField(default=0),
        ),
    ]
