# Generated by Django 2.2.6 on 2020-06-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0027_auto_20200604_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='operation_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('user', models.TextField()),
                ('operation', models.TextField()),
                ('api', models.TextField()),
            ],
        ),
    ]
