# Generated by Django 2.2.3 on 2020-06-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0029_auto_20200625_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startuptime',
            old_name='type',
            new_name='scene',
        ),
    ]
