# Generated by Django 2.2.3 on 2020-06-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0030_auto_20200625_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='remark',
            new_name='scene',
        ),
    ]
