# Generated by Django 2.2.3 on 2020-06-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0031_auto_20200625_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='status',
            field=models.TextField(default='Offline'),
        ),
        migrations.AddField(
            model_name='startuptime',
            name='status',
            field=models.TextField(default='Offline'),
        ),
    ]
