# Generated by Django 2.2.3 on 2020-06-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0032_auto_20200625_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='apkname',
        ),
        migrations.RemoveField(
            model_name='startuptime',
            name='apkname',
        ),
        migrations.RemoveField(
            model_name='startuptime',
            name='firsttime',
        ),
        migrations.RemoveField(
            model_name='startuptime',
            name='secondtime',
        ),
    ]
