# Generated by Django 2.2.3 on 2020-07-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0033_auto_20200629_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugMonitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.TextField()),
                ('project', models.TextField()),
                ('bugs', models.IntegerField()),
                ('ctime', models.DateTimeField()),
            ],
        ),
    ]
