# Generated by Django 2.2.3 on 2020-07-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0036_bi_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='applog',
            name='app_config',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='applog',
            name='mediation_config',
            field=models.TextField(default=''),
        ),
    ]
