# Generated by Django 2.2.3 on 2020-07-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0037_auto_20200714_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_debug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('debug', models.TextField()),
            ],
        ),
    ]
