# Generated by Django 2.2.3 on 2020-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0038_app_debug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_debug',
            name='debug',
            field=models.IntegerField(),
        ),
    ]
