# Generated by Django 2.2.6 on 2020-07-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0039_auto_20200715_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='bi_actions',
            name='anm',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bi_actions',
            name='did',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bi_actions',
            name='ver',
            field=models.TextField(default=''),
        ),
    ]
