# Generated by Django 2.2.6 on 2020-07-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0040_auto_20200716_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='bi_actions',
            name='ext',
            field=models.TextField(default=''),
        ),
    ]
