# Generated by Django 2.2.6 on 2020-08-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0041_bi_actions_ext'),
    ]

    operations = [
        migrations.CreateModel(
            name='jmeter_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('build_num', models.TextField(default='')),
                ('simpleNum', models.TextField(default='')),
                ('avg', models.TextField(default='')),
                ('median', models.TextField(default='')),
                ('percent90', models.TextField(default='')),
                ('percent95', models.TextField(default='')),
                ('percent99', models.TextField(default='')),
                ('min', models.TextField(default='')),
                ('max', models.TextField(default='')),
                ('error', models.TextField(default='')),
                ('throughput', models.TextField(default='')),
                ('send', models.TextField(default='')),
                ('url', models.TextField(default='')),
                ('params', models.TextField(default='')),
                ('treadNum', models.TextField(default='')),
                ('loopNum', models.TextField(default='')),
                ('rampUp', models.TextField(default='')),
            ],
        ),
    ]
