# Generated by Django 2.2.6 on 2020-08-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0042_jmeter_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ding_build_apk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anm', models.TextField()),
                ('env', models.TextField(default='debug')),
                ('jobname', models.TextField()),
                ('parameters', models.TextField(default='')),
            ],
        ),
    ]
