# Generated by Django 2.2.6 on 2020-08-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0043_ding_build_apk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ding_jira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('jira_id', models.TextField()),
                ('assignee', models.TextField()),
            ],
        ),
    ]
