# Generated by Django 2.2.6 on 2020-08-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0044_ding_jira'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_applog',
            name='subanm',
            field=models.TextField(default=''),
        ),
    ]
