# Generated by Django 2.2.6 on 2020-09-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0045_server_applog_subanm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ai_test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('name', models.TextField()),
                ('all_num', models.TextField()),
                ('ai_win', models.TextField(default=0)),
                ('win_rate', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
