# Generated by Django 2.2.6 on 2020-09-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0046_ai_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ai_test',
        ),
    ]
