# Generated by Django 2.2.6 on 2020-10-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0047_delete_ai_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ding_key_msg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.TextField()),
                ('msg', models.TextField()),
                ('pic_url', models.TextField()),
                ('pic_top', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ding_pkgname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('pkgname', models.TextField()),
            ],
        ),
    ]
