# Generated by Django 2.2.6 on 2020-10-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0048_ding_key_msg_ding_pkgname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ding_key_msg',
            name='sort',
            field=models.TextField(default='基建'),
        ),
    ]
