# Generated by Django 2.2.3 on 2020-10-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0049_ding_key_msg_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.TextField()),
                ('status', models.TextField(default='')),
                ('operate', models.TextField(default='')),
                ('dtime', models.DateTimeField()),
            ],
        ),
    ]
