# Generated by Django 2.2.6 on 2020-12-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0051_user_admin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anm',
            field=models.TextField(null=True),
        ),
    ]
