# Generated by Django 2.2.6 on 2020-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0052_user_anm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anm',
            field=models.TextField(default=''),
        ),
    ]
