# Generated by Django 2.2.6 on 2020-12-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0053_auto_20201208_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anm',
            field=models.TextField(null=True),
        ),
    ]
