# Generated by Django 3.1.7 on 2021-03-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0054_auto_20201208_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='api',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='request_name',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='response_name',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
